### 로그인
POST {{server}}/users/signin
Content-Type: application/json

{
  "email": "cjdeks@hanmail.net",
  "password": "abc1234!"
}

### 가입
POST {{server}}/users/signup
Content-Type: application/json

{
  "email": "cjdeks@hanmail.net",
  "name": "청단",
  "gender": "M",
  "password": "abc1234!"
}

### 이메일 체크
GET {{server}}/users/email-check?email=hkhong91@gmail.com

### 이름 체크
GET {{server}}/users/name-check?name=청

### 권한 추가
POST {{server}}/users/me/authorities
Authorization: {{jwt2}}
Content-Type: application/json

{
  "authority": "SELLER"
}