### 로그인
POST {{server}}/auth/signin
Content-Type: application/json

{
  "email": "hkhong91@gmail.com",
  "password": "1234"
}

### 가입
POST {{server}}/auth/signup
Content-Type: application/json

{
  "email": "cjdeks@hanmail.net",
  "name": "청단",
  "gender": "M",
  "password": "1234"
}