### 책 조회
GET {{server}}/books/60f6fd94a984e31ac6ce2cb6

### 책 조회
GET {{server}}/books/60f6fd94a984e31ac6ce2cb6
Authorization: Bearer {{jwt1}}

### 책 리스트 조회
GET {{server}}/books

### 책 리스트 조회
GET {{server}}/books
Authorization: Bearer {{jwt1}}

### 책 등록
POST {{server}}/books
Content-Type: application/json

{
  "title": "MongoDB 완벽 가이드",
  "introduction": "NOSQL의 진수 몽고DB 개발부터 관리까지",
  "authors": [
    "크리스티나 초도로우"
  ],
  "publishedDate": "2021-03-22"
}

### 책 수정
PATCH {{server}}/books/60f7f3b01540627601cd1bc8
Content-Type: application/json

{
  "title": "몽고디비 인 액션",
  "introduction": "빅 데이터 시대 최고의 NoSQL 데이터베이스!",
  "authors": [
    "카일 뱅커",
    "피터 배컴",
    "숀 버크",
    "덕 개릿",
    "팀 호킨스"
  ],
  "publishedDate": "2021-05-02"
}

### 책 삭제
DELETE {{server}}/books/60f6fd94a984e31ac6ce2cb6

### 책 좋아요/싫어요
PUT {{server}}/books/60f7f3b01540627601cd1bc8/like-or-hate
Authorization: Bearer {{jwt2}}
Content-Type: application/json

{
  "likeOrHate": "LIKE"
}