###
GET http://localhost:8080/books/60ed38c2e817435eb9fd5699

###
GET http://localhost:8080/books

###
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "TDD",
  "authors": [
    "Kent"
  ],
  "publishedYear": 2021
}

###
PUT http://localhost:8080/books/60ed38c2e817435eb9fd5699
Content-Type: application/json

{
  "title": "TDD",
  "authors": [
    "Kent"
  ],
  "publishedYear": 2021
}

###
PATCH http://localhost:8080/books/60ed38c2e817435eb9fd5699
Content-Type: application/json

{
  "title": "Webflux",
  "authors": [
    "Rupee"
  ],
  "publishedYear": 2021
}

###
DELETE http://localhost:8080/books/60ed3cca8b089e41ff2f9951