### 댓글 조회
GET {{server}}/books/60f94272cbf48603a3a6439d/reviews

### 댓글 작성
POST {{server}}/books/60f94272cbf48603a3a6439d/reviews
Authorization: {{jwt1}}
Content-Type: application/json

{
  "content": "내용"
}

### 댓글 수정
PATCH {{server}}/books/60f94272cbf48603a3a6439d/reviews/60f985d55eba3a6eced65b7e
Authorization: {{jwt1}}
Content-Type: application/json

{
  "content": "내용4"
}

### 댓글 삭제
DELETE {{server}}/books/60f94272cbf48603a3a6439d/reviews/60f98f03054b2117559ca4b6
Authorization: {{jwt1}}