### 책 조회
GET {{server}}/books/61051fa985de2038eccc5393

### 책 조회
GET {{server}}/books/61053b9f1f8efc2768bf2001/read
Authorization: {{jwt1}}

### 책 리스트 조회
GET {{server}}/books

### 책 리스트 조회
GET {{server}}/books/read
Authorization: {{jwt1}}

### 책 등록
POST {{server}}/books
Authorization: {{jwt2}}
Content-Type: application/json

{
  "title": "MongoDB 완벽 가이드",
  "introduction": "NOSQL의 진수 몽고DB 개발부터 관리까지",
  "authors": [
    "크리스티나 초도로우"
  ],
  "publishedDate": "2021-03-22"
}

### 책 수정
PATCH {{server}}/books/610521d4ae15391e20ec6538
Authorization: {{jwt1}}
Content-Type: application/json

{
  "title": "몽고디비 인 액션",
  "introduction": "빅 데이터 시대 최고의 NoSQL 데이터베이스!",
  "authors": [
    "카일 뱅커",
    "피터 배컴",
    "숀 버크",
    "덕 개릿",
    "팀 호킨스"
  ],
  "publishedDate": "2021-05-02"
}

### 책 카테고리 추가
PUT {{server}}/books/61051fa985de2038eccc5393/categories
Authorization: {{jwt1}}
Content-Type: application/json

{
  "categoryCodes": [
    "IT"
  ]
}

### 책 삭제
DELETE {{server}}/books/60fcc372030699554e4e66c5
Authorization: {{jwt1}}

### 책 조회수 집계
PUT {{server}}/books/hits