### 댓글 조회
GET {{server}}/books/60fc292745ed2c1c3058ff79/reviews

### 댓글 작성
POST {{server}}/books/61051fa985de2038eccc5393/reviews
Authorization: {{jwt1}}
Content-Type: application/json

{
  "content": "내용"
}

### 댓글 수정
PATCH {{server}}/books/60fc292745ed2c1c3058ff79/reviews/60fc39ee5cdbb82de688ab03
Authorization: {{jwt1}}
Content-Type: application/json

{
  "content": "내용4"
}

### 댓글 삭제
DELETE {{server}}/books/60fc292745ed2c1c3058ff79/reviews/60fc39f15cdbb82de688ab04
Authorization: {{jwt1}}